language: generic

sudo: required # Super user level permissions are needed
services:
  - docker # Travis CI  is going to install Docker engine

before_install:
  - docker build -t safeyhalim/docker-react -f Dockerfile.dev . # Tell Travis CI to build the Docker image from the development Dockerfile and giving it a tag name to be able to easily refer to it in the future (we cannot copy the image-id in case of Travis CI automated commands)

script: # Travis CI commands to run the test suite. Travis CI is going to observe the result of each of the commands. If anyone returns anything other than 0, Travis CI is going to assume that the testing has failed
  - docker run -e CI=true safeyhalim/docker-react npm run test -- --coverage # the -- --coverage is a flag specific to npm run test to make sure that the command exits at the end (the default behaviour is that it doesn't and waits for user action. We must make sure it exists so that Travis CI knows that the test has finished execution)
     # -e flag sets an environment variable in the Docker container CI=true is an environment varialble specific to the create-react-app project to allow it to run in a CI pipeline